name: newstech
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/exampleimage.jpg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: TitleCroiss
      fonts:
        - asset: assets/fonts/CroissantOne-Regular.ttf

    - family: TitleNewsRoslab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf

    - family: SourceSans
      fonts:
        - asset: assets/fonts/SourceSans3-Regular.ttf
    
    - family: ArchiveBlack
      fonts:
        - asset: assets/fonts/ArchivoBlack-Regular.ttf
